# hosts.yaml — добавь в репо все хосты, которые надо мониторить
# name: удобное имя
# host: домен или IP
# port: порт TCP
# enabled: true/false

- name: WPC 1 Denyarich
  host: 7.tcp.ngrok.io
  port: 21232
  enabled: true

- name: WPC 2 Perro123
  host: 7.tcp.ngrok.io
  port: 21267
  enabled: true

# Пример ngrok (только если у вас reserved domain или статический адрес)
- name: WPC 3 flugegeheimen
  host: 7.tcp.ngrok.io
  port: 22607
  enabled: true

- name: WPC 4 Redondito1
  host: cristian-host.ddns.net
  port: 3389
  enabled: true

- name: WPC 4 Redondito1 ngrok
  host: 7.tcp.ngrok.io
  port: 22591
  enabled: true

- name: DPC 1 vkmovineitor
  host: tania-host.ddns.net
  port: 3389
  enabled: true

- name: DPC 1 vkmovineitor ngrok
  host: 7.tcp.ngrok.io
  port: 27302
  enabled: true

- name: DPC 2 DaLeFer
  host: lucas-host.ddns.net
  port: 3389
  enabled: true

- name: DPC 2 DaLeFer ngrok
  host: 3.tcp.ngrok.io
  port: 27951
  enabled: true

- name: DPC 3 MACOCO
  host: candela-host.ddns.net
  port: 3389
  enabled: true

- name: DPC 3 MACOCO ngrok
  host: 5.tcp.ngrok.io
  port: 21764
  enabled: true

- name: DPC 4 ElKapo
  host: agus2-host.ddns.net
  port: 3389
  enabled: true

- name: DPC 4 ElKapo ngrok
  host: 3.tcp.ngrok.io
  port: 27677
  enabled: true

- name: DPC 5 remanso
  host: roman-host.ddns.net
  port: 3389
  enabled: true

- name: DPC 5 remanso ngrok
  host: 5.tcp.ngrok.io
  port: 21766
  enabled: true

- name: DPC 6 LaJefa
  host: vanesa-host.ddns.net
  port: 3389
  enabled: true

- name: DPC 6 LaJefa ngrok
  host: 5.tcp.ngrok.io
  port: 24298
  enabled: true

- name: remoto
  host: 5.tcp.ngrok.io
  port: 27564
  enabled: true
  
